apiVersion: pki.vault.m.upbound.io/v1alpha1
kind: SecretBackendCrlConfig
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1alpha1/secretbackendcrlconfig
  labels:
    testing.upbound.io/example-name: crl_config
  name: crl-config
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: pki
    disable: false
    expiry: 72h

---

apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1alpha1/secretbackendcrlconfig
  labels:
    testing.upbound.io/example-name: pki
  name: pki
  namespace: upbound-system
spec:
  forProvider:
    defaultLeaseTtlSeconds: 3600
    maxLeaseTtlSeconds: 86400
    path: '%s'
    type: pki
