apiVersion: pki.vault.m.upbound.io/v1alpha1
kind: SecretBackendConfigCA
metadata:
  annotations:
    meta.upbound.io/example-id: pki/v1alpha1/secretbackendconfigca
  labels:
    testing.upbound.io/example-name: intermediate
  name: intermediate
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: intermediate
    pemBundleSecretRef:
      key: example-key
      name: example-secret
