apiVersion: consul.vault.m.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: consul/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    address: 127.0.0.1:8500
    description: Manages the Consul backend
    path: consul
    tokenSecretRef:
      key: example-key
      name: example-secret
