apiVersion: database.vault.m.upbound.io/v1alpha1
kind: SecretBackendStaticRole
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/secretbackendstaticrole
  labels:
    testing.upbound.io/example-name: period_role
  name: period-role
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: db
    dbNameSelector:
      matchLabels:
        testing.upbound.io/example-name: postgres
    name: my-period-role
    rotationPeriod: "3600"
    rotationStatements:
    - ALTER USER "{{name}}" WITH PASSWORD '{{password}}';
    username: example

---

apiVersion: database.vault.m.upbound.io/v1alpha1
kind: SecretBackendConnection
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/secretbackendstaticrole
  labels:
    testing.upbound.io/example-name: postgres
  name: postgres
  namespace: upbound-system
spec:
  forProvider:
    allowedRoles:
    - '*'
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: postgres
    postgresql:
    - connectionUrl: postgres://username:password@host:port/database

---

apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/secretbackendstaticrole
  labels:
    testing.upbound.io/example-name: db
  name: db
  namespace: upbound-system
spec:
  forProvider:
    path: postgres
    type: database
