apiVersion: token.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: token/v1alpha1/authbackendrole
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    roleName: "app"
  providerConfigRef:
    name: vault-provider-config
