apiVersion: kv.vault.m.upbound.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds
  namespace: vault
spec:
  forProvider:
    path: "kvv1/vault-creds"
    dataJsonSecretRef:
      name: vault-creds
      key: credentials
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
---
apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds-kv1
  namespace: vault
spec:
  forProvider:
    path: "kvv1"
    type: "kv"
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
