apiVersion: github.vault.m.upbound.io/v1alpha1
kind: AuthBackend
metadata:
  annotations:
    meta.upbound.io/example-id: github/v1alpha1/authbackend
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    organization: myorg
