apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/mount
  labels:
    testing.upbound.io/example-name: generic
  name: generic
  namespace: vault
spec:
  forProvider:
    path: "generic"
    type: "generic"
  providerConfigRef:
    kind: ClusterProvicerConfig
    name: vault-provider-config
