apiVersion: kv.vault.m.upbound.io/v1alpha1
kind: SecretBackendV2
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secretbackendv2
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    casRequired: true
    deleteVersionAfter: 12600
    maxVersions: 5
    mountSelector:
      matchLabels:
        testing.upbound.io/example-name: kvv2

---

apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secretbackendv2
  labels:
    testing.upbound.io/example-name: kvv2
  name: kvv2
  namespace: upbound-system
spec:
  forProvider:
    description: KV Version 2 secret engine mount
    options:
      version: "2"
    path: kvv2
    type: kv
