apiVersion: kubernetes.vault.m.upbound.io/v1alpha1
kind: AuthBackendConfig
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/authbackendconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: kubernetes
    disableIssValidation: "true"
    issuer: api
    kubernetesCaCert: |-
      -----BEGIN CERTIFICATE-----
      example
      -----END CERTIFICATE-----
    kubernetesHost: http://example.com:443
    tokenReviewerJwtSecretRef:
      key: example-key
      name: example-secret

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: kubernetes/v1alpha1/authbackendconfig
  labels:
    testing.upbound.io/example-name: kubernetes
  name: kubernetes
  namespace: upbound-system
spec:
  forProvider:
    type: kubernetes
