apiVersion: generic.vault.m.upbound.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: generic/v1alpha1/endpoint
  labels:
    testing.upbound.io/example-name: u1
  name: u1
  namespace: upbound-system
spec:
  forProvider:
    dataJsonSecretRef:
      key: example-key
      name: example-secret
    ignoreAbsentFields: true
    path: auth/userpass/users/u1

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: generic/v1alpha1/endpoint
  labels:
    testing.upbound.io/example-name: userpass
  name: userpass
  namespace: upbound-system
spec:
  forProvider:
    type: userpass
