apiVersion: generic.vault.m.upbound.io/v1alpha1
kind: Secret
metadata:
  annotations:
    meta.upbound.io/example-id: generic/v1alpha1/secret
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    dataJsonSecretRef:
      key: example-key
      name: example-secret
    path: secret/foo
