apiVersion: aws.vault.m.upbound.io/v1alpha1
kind: AuthBackendIdentityWhitelist
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendidentitywhitelist
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    safetyBuffer: 3600

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendidentitywhitelist
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    type: aws
