apiVersion: aws.vault.m.upbound.io/v1alpha1
kind: AuthBackendClient
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendclient
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    identityTokenAudience: <TOKEN_AUDIENCE>
    identityTokenTtl: <TOKEN_TTL>
    roleArn: <AWS_ROLE_ARN>
    rotationSchedule: 0 * * * SAT
    rotationWindow: 3600

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/authbackendclient
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    type: aws
