apiVersion: aws.vault.m.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: aws/v1alpha1/secretbackend
  labels:
    testing.upbound.io/example-name: aws
  name: aws
  namespace: upbound-system
spec:
  forProvider:
    accessKeySecretRef:
      key: example-key
      name: example-secret
    rotationSchedule: 0 * * * SAT
    rotationWindow: 3600
    secretKeySecretRef:
      key: example-key
      name: example-secret
