apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/mount
  labels:
    testing.upbound.io/example-name: kv-v1
  name: kv-v1
spec:
  deletionPolicy: Delete
  forProvider:
    path: "kvv1"
    type: "kv-v1"
  providerConfigRef:
    name: vault-provider-config
