apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/mount
  labels:
    testing.upbound.io/example-name: generic
  name: generic
spec:
  deletionPolicy: Delete
  forProvider:
    path: "generic"
    type: "generic"
  providerConfigRef:
    name: vault-provider-config
