apiVersion: azure.vault.m.upbound.io/v1alpha1
kind: AuthBackendConfig
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/authbackendconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    clientIdSecretRef:
      key: example-key
      name: example-secret
    identityTokenAudience: <TOKEN_AUDIENCE>
    identityTokenTtl: <TOKEN_TTL>
    rotationSchedule: 0 * * * SAT
    rotationWindow: 3600
    tenantIdSecretRef:
      key: example-key
      name: example-secret

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/authbackendconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    identityTokenKey: example-key
    type: azure
