apiVersion: azure.vault.m.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: generated_role
  name: generated-role
  namespace: upbound-system
spec:
  forProvider:
    azureRoles:
    - roleName: Reader
      scope: /subscriptions/${var.subscription_id}/resourceGroups/azure-vault-group
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: azure
    maxTtl: 600
    role: generated_role
    signInAudience: AzureADMyOrg
    tags:
    - team:engineering
    - environment:development
    ttl: 300

---

apiVersion: azure.vault.m.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: azure/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: azure
  name: azure
  namespace: upbound-system
spec:
  forProvider:
    clientIdSecretRef:
      key: example-key
      name: example-secret
    clientSecretSecretRef:
      key: example-key
      name: example-secret
    subscriptionIdSecretRef:
      key: example-key
      name: example-secret
    tenantIdSecretRef:
      key: example-key
      name: example-secret
