apiVersion: mfa.vault.m.upbound.io/v1alpha1
kind: Okta
metadata:
  annotations:
    meta.upbound.io/example-id: mfa/v1alpha1/okta
  labels:
    testing.upbound.io/example-name: my_okta
  name: my-okta
  namespace: upbound-system
spec:
  forProvider:
    apiTokenSecretRef:
      key: example-key
      name: example-secret
    mountAccessorSelector:
      matchLabels:
        testing.upbound.io/example-name: userpass
    name: my_okta
    orgName: hashicorp
    usernameFormat: user@example.com

---

apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: mfa/v1alpha1/okta
  labels:
    testing.upbound.io/example-name: userpass
  name: userpass
  namespace: upbound-system
spec:
  forProvider:
    path: userpass
    type: userpass
