apiVersion: vault.vault.m.upbound.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/token
  labels:
    testing.upbound.io/example-name: vault-token
  name: vault-token
  namespace: vault
spec:
  forProvider:
    roleName: "app"
    ttl: "24h"
    renewMinLease: 43200
    renewIncrement: 86400
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
---
apiVersion: token.vault.m.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: vault/v1alpha1/token
  labels:
    testing.upbound.io/example-name: vault-token
  name: vault-token
  namespace: vault
spec:
  forProvider:
    roleName: "app"
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
