apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: MfaOkta
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/mfaokta
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    apiTokenSecretRef:
      key: example-key
      name: example-secret
    baseUrl: qux.baz.com
    orgName: org1
