apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcClient
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcclient
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    accessTokenTtl: 7200
    assignmentsRefs:
    - name: test
    idTokenTtl: 2400
    name: my-app
    redirectUris:
    - http://127.0.0.1:9200/v1/auth-methods/oidc:authenticate:callback
    - http://127.0.0.1:8251/callback
    - http://127.0.0.1:8080/callback

---

apiVersion: identity.vault.m.upbound.io/v1alpha1
kind: OidcAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: identity/v1alpha1/oidcclient
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    entityIdsRefs:
    - name: example
    groupIdsRefs:
    - name: example
    name: my-assignment
