apiVersion: terraform.vault.m.upbound.io/v1alpha1
kind: CloudSecretCreds
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1alpha1/cloudsecretcreds
  labels:
    testing.upbound.io/example-name: token
  name: token
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: terraform.vault.m.upbound.io/v1alpha1
kind: CloudSecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1alpha1/cloudsecretcreds
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    backend: terraform
    description: Manages the Terraform Cloud backend
    tokenSecretRef:
      key: example-key
      name: example-secret

---

apiVersion: terraform.vault.m.upbound.io/v1alpha1
kind: CloudSecretRole
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1alpha1/cloudsecretcreds
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    name: test-role
    organization: example-organization-name
    teamId: team-ieF4isC...
