apiVersion: terraform.vault.m.upbound.io/v1alpha1
kind: CloudSecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: terraform/v1alpha1/cloudsecretbackend
  labels:
    testing.upbound.io/example-name: test
  name: test
  namespace: upbound-system
spec:
  forProvider:
    backend: terraform
    description: Manages the Terraform Cloud backend
    tokenSecretRef:
      key: example-key
      name: example-secret
