apiVersion: rabbitmq.vault.m.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: role
  name: role
  namespace: upbound-system
spec:
  forProvider:
    backendSelector:
      matchLabels:
        testing.upbound.io/example-name: rabbitmq
    name: deploy
    tags: tag1,tag2
    vhost:
    - configure: ""
      host: /
      read: .*
      write: ""
    vhostTopic:
    - host: /
      vhost:
      - read: .*
        topic: amq.topic
        write: ""

---

apiVersion: rabbitmq.vault.m.upbound.io/v1alpha1
kind: SecretBackend
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/secretbackendrole
  labels:
    testing.upbound.io/example-name: rabbitmq
  name: rabbitmq
  namespace: upbound-system
spec:
  forProvider:
    connectionUri: https://.....
    passwordSecretRef:
      key: example-key
      name: example-secret
    usernameSecretRef:
      key: example-key
      name: example-secret
