apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secretv2
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds
spec:
  forProvider:
    mount: "kvv2"
    name: "vault-creds"
    cas: 1
    customMetadata:
      - maxVersions: 99
        deleteVersionAfter: 6000
    dataJsonSecretRef:
      name: vault-creds
      namespace: vault
      key: credentials
  providerConfigRef:
    name: vault-provider-config
---
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secretv2
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-creds-kv2
spec:
  deletionPolicy: Delete
  forProvider:
    path: "kvv2"
    type: "kv-v2"
  providerConfigRef:
    name: vault-provider-config
