apiVersion: github.vault.m.upbound.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: github/v1alpha1/team
  labels:
    testing.upbound.io/example-name: github-team
  name: github-team
spec:
  forProvider:
    backend: "github"
    team: "everyone"
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
---
apiVersion: auth.vault.m.upbound.io/v1alpha1
kind: Backend
metadata:
  annotations:
    meta.upbound.io/example-id: github/v1alpha1/team
  labels:
    testing.upbound.io/example-name: github-team
  name: github-team
  namespace: vault
spec:
  forProvider:
    description: "GitHub generic auth backend for UXP managed Vault"
    type: "github"
  providerConfigRef:
    kind: ClusterProviderConfig
    name: vault-provider-config
